"Resource/UI/TradingStartDialog.res"
{
	"TradingStartDialog"
	{
		"fieldName"		"TradingStartDialog"
		"visible"		"1"
		"enabled"		"1"
		"xpos"		"cs-0.5"
		"ypos"		"130"
		"wide"		"300"
		"tall"		"200"
		"bgcolor_override"		"Blank"
		"settitlebarvisible"	""
		"border"		"MaterialGrayDarkest"

		"button_kv"
		{
			"xpos"		"10"
			"ypos"		"0"
			"wide"		"278"
			"tall"		"22"

			"button"
			{
				"xpos"		"0"
				"ypos"		"0"
				"wide"		"278"
				"tall"		"22"
				"visible"		"1"
				"enabled"		"1"
				"labelText"		""
				"font"		"Size 16"
				"textAlignment"	"west"
				"textinsetx"	"20"
				"use_proportional_insets" "1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
			}
			"avatar"
			{
				"ControlName"	"CAvatarImagePanel"
				"fieldName"		"avatar"
				"xpos"		"2"
				"ypos"		"2"
				"zpos"		"1"
				"wide"		"18"
				"tall"		"18"
				"image"		""
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
				"color_outline"	"MainTheme"
			}
		}
	}

	"PlayerListScroller"
	{
		"ControlName"	"ScrollableEditablePanel"
		"fieldName"		"PlayerListScroller"
		"xpos"		"5"
		"ypos"		"30"
		"wide"		"290"
		"tall"		"130"
		"PaintBackgroundType"	"0"
		"fgcolor_override"	"White"
		"bgcolor_override"	"TransparentBlack"

		"PlayerList"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"PlayerList"
			"xpos"		"2"
			"ypos"		"0"
			"wide"		"278"
			"tall"		"130"
			"visible"		"1"
		}
	}

	"StatePanel0"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"StatePanel0"
		"visible"		"1"
		"enabled"		"1"
		"xpos"		"0"
		"ypos"					0
		"wide"		"300"
		"tall"		"180"
		"PaintBackgroundType"	"0"

		"QueryLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"QueryLabel"
			"font"		"Size 20"
			"labelText"		"#TF_TradeStartDialog_Select"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"10"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"20"
			"visible"		"0"
			"enabled"		"0"
			"fgcolor_override" "White"
		}
		"subbutton0"
		{
			"ControlName"	"CExButton"
			"fieldName"		"subbutton0"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"R"
			"font"			"Symbols 64"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"Command"		"friends"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"armedfgcolor_override"		"MainTheme"
			
			"paintbackground"	"0"
			
			"pin_to_sibling" 		"subbutton1"
			"pin_corner_to_sibling" "PIN_TOPRIGHT"
			"pin_to_sibling_corner" "PIN_TOPLEFT"
		}
		"sublabel0"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"sublabel0"
			"font"			"Size 12"
			"labelText"		"#TF_TradeStartDialog_SelectFriends"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"11"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" 		"White"
			"fgcolor" 				"White"
			
			"AllCaps"				"1"
			
			"pin_to_sibling" 		"subbutton0"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		}
		"subbutton1"
		{
			"ControlName"	"CExButton"
			"fieldName"		"subbutton1"
			"xpos"			"105"
			"ypos"			"50"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"u"
			"font"			"Symbols 64"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"Command"		"server"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"armedfgcolor_override"		"MainTheme"
			
			"paintbackground"	"0"
		}
		"sublabel1"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"sublabel1"
			"font"			"Size 12"
			"labelText"		"#TF_TradeStartDialog_SelectServer"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"11"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" 		"White"
			"fgcolor" 				"White"
			
			"AllCaps"				"1"
			
			"pin_to_sibling" 		"subbutton1"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		}
		"subbutton2"
		{
			"ControlName"	"CExButton"
			"fieldName"		"subbutton2"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"p"
			"font"			"Symbols 64"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"Command"		"profile"
			"sound_depressed"		"UI/buttonclick.wav"
			"sound_released"		"UI/buttonclickrelease.wav"
			"armedfgcolor_override"		"MainTheme"
			
			"paintbackground"		"0"
			
			"pin_to_sibling" 		"subbutton1"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
		}
		"sublabel2"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"sublabel2"
			"font"			"Size 12"
			"labelText"		"#TF_TradeStartDialog_SelectProfile"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"90"
			"tall"			"11"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" 		"White"
			"fgcolor" 				"White"
			
			"AllCaps"				"1"
			
			"pin_to_sibling" 		"subbutton2"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		}
	}
	"StatePanel1"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"StatePanel1"
		"visible"		"1"
		"enabled"		"1"
		"xpos"		"0"
		"ypos"					0
		"wide"		"300"
		"tall"		"180"
		"PaintBackgroundType"	"0"

		"QueryLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"QueryLabel"
			"font"		"Size 20"
			"labelText"		"#TF_TradeStartDialog_Friends"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"10"
			"wide"		"300"
			"tall"		"20"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "White"
		}
		"EmptyPlayerListLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"EmptyPlayerListLabel"
			"font"		"Size 16"
			"labelText"		"#TF_TradeStartDialog_FriendsNone"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"60"
			"zpos"		"1"
			"wide"		"300"
			"tall"		"30"
			"visible"		"1"
			"enabled"		"1"
			"wrap"		"1"
			"centerwrap"	"1"
			"fgcolor_override" "White"
		}
	}
	"StatePanel2"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"StatePanel2"
		"visible"		"1"
		"enabled"		"1"
		"xpos"		"0"
		"ypos"					0
		"wide"		"300"
		"tall"		"180"
		"PaintBackgroundType"	"0"

		"QueryLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"QueryLabel"
			"font"		"Size 20"
			"labelText"		"#TF_TradeStartDialog_Server"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"10"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"20"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "White"
		}
		"EmptyPlayerListLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"EmptyPlayerListLabel"
			"font"		"Size 16"
			"labelText"		"#TF_TradeStartDialog_ServerNone"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"60"
			"zpos"		"1"
			"wide"		"300"
			"tall"		"30"
			"visible"		"1"
			"enabled"		"1"
			"wrap"		"1"
			"centerwrap"	"1"
			"fgcolor_override" "White"
		}
	}
	"StatePanel3"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"StatePanel3"
		"visible"		"1"
		"enabled"		"1"
		"xpos"		"0"
		"ypos"					0
		"wide"		"300"
		"tall"		"180"
		"PaintBackgroundType"	"0"

		"QueryLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"QueryLabel"
			"font"		"Size 20"
			"labelText"		"#TF_TradeStartDialog_Profile"
			"textAlignment"	"north"
			"xpos"		"0"
			"ypos"		"10"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"20"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "White"
		}
		"URLHelpLabel"
		{
			"ControlName"	"Label"
			"fieldName"		"URLHelpLabel"
			"font"		"Size 11"
			"labelText"		"#TF_TradeStartDialog_ProfileHelp"
			"textAlignment"	"center"
			"xpos"		"0"
			"ypos"		"40"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"30"
			"visible"		"1"
			"enabled"		"1"
			"wrap"		"1"
			"centerwrap"	"1"
			"fgcolor_override" "WhiteGray"
		}
		"URLFailLabel"
		{
			"ControlName"	"Label"
			"fieldName"		"URLFailLabel"
			"font"		"Size 11"
			"labelText"		"#TF_TradeStartDialog_ProfileFail"
			"textAlignment"	"center"
			"xpos"		"0"
			"ypos"		"105"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"40"
			"visible"		"0"
			"enabled"		"1"
			"wrap"		"1"
			"centerwrap"	"1"
			"fgcolor_override" "Red"
		}
		"URLSearchingLabel"
		{
			"ControlName"	"Label"
			"fieldName"		"URLSearchingLabel"
			"font"		"Size 11"
			"labelText"		"#TF_TradeStartDialog_ProfileLookup"
			"textAlignment"	"center"
			"xpos"		"0"
			"ypos"		"105"
			"zpos"		"-1"
			"wide"		"300"
			"tall"		"40"
			"visible"		"0"
			"enabled"		"1"
			"wrap"		"1"
			"centerwrap"	"1"
			"fgcolor_override" "Red"
		}
		"URLEntry"
		{
			"ControlName"		"TextEntry"
			"fieldName"		"URLEntry"
			"xpos"		"cs-0.5"
			"ypos"		"80"
			"wide"		"290"
			"tall"		"24"
			"visible"		"1"
			"enabled"		"1"
			"textHidden"		"0"
			"editable"		"1"
			"maxchars"		"256"
			"NumericInputOnly"	"0"
			"unicode"		"0"
			"wrap"		"0"
			"proportionaltoparent"		"1"
			"fgcolor_override"	"White"
			"bgcolor_override"	"TransparentBlack"
			"selectionColor_override" "MainTheme"
			"paintbackgroundtype" "0"
			"labelText"		""
			"font"		"Size 14"
			"textAlignment"		"west"
		}
		"subbutton0"
		{
			"ControlName"	"CExButton"
			"fieldName"		"subbutton0"
			"xpos"		"cs-0.5"
			"ypos"		"114"
			"zpos"		"1"
			"wide"		"290"
			"tall"		"25"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#TF_TradeStartDialog_ProfileGo"
			"font"		"Size 16"
			"textAlignment"	"center"
			"Command"		"url_ok"
			"proportionaltoparent"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
		}
	}

	"CancelButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"CancelButton"
		"xpos"		"cs-0.5"
		"ypos"		"170"
		"zpos"		"1"
		"wide"		"290"
		"tall"		"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cancel"
		"font"		"Size 16"
		"textAlignment"	"center"
		"Command"		"cancel"
		"proportionaltoparent"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
}
